CREATE TABLE SHIPWRECK(
  ID INT AUTO_INCREMENT,
  NAME VARCHAR(255),
  DESCRIPTION VARCHAR(2000),
  CONDITION VARCHAR(255),
  DEPTH INT,
  LATTITUDE DOUBLE,
  LONGITUDE DOUBLE,
  YEAR_DISCOVERED INT
);
